import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Items from "@/widgets/MainPage/Items";
import Greeting from "@/widgets/MainPage/Greeting";
import { motion } from "framer-motion";
import { useTranslations } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const t = useTranslations();

  return (
    <>
      <Head>
        <title>Kenzy Person</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script
            type="text/javascript"
            src="https://cdn.weglot.com/weglot.min.js"
          ></script>
          <script
            dangerouslySetInnerHTML={{
              __html: `
                Weglot.initialize({
                  api_key: 'wg_e2e0c824a865f70f5acb2af1c4d3bde61'
                });
              `,
            }}
          />      
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 0.6 }}
        transition={{ duration: 1.3 }}
        className={styles.main}
      >
        <div className={styles.innerBlock}>
          <Greeting />
          <br />
          <Items />
        </div>
      </motion.main>
    </>
  );
}
